import { Template } from '../types';
import { v4 as uuidv4 } from 'uuid';

export const templates: Template[] = [
  {
    id: 'simple-mindmap',
    name: 'Simple Mind Map',
    description: 'A basic mind map with central topic and branches',
    preview: '🧠',
    nodes: [
      {
        id: 'central',
        type: 'circle',
        position: { x: 400, y: 300 },
        data: {
          label: 'Central Topic',
          color: '#ffffff',
          backgroundColor: '#3B82F6',
          borderColor: '#1E40AF',
          fontSize: 16,
          fontWeight: 'bold',
          borderWidth: 2,
        },
      },
      {
        id: 'branch1',
        type: 'rectangle',
        position: { x: 200, y: 150 },
        data: {
          label: 'Branch 1',
          color: '#1F2937',
          backgroundColor: '#E5E7EB',
          borderColor: '#9CA3AF',
          fontSize: 14,
          fontWeight: 'normal',
          borderWidth: 1,
        },
      },
      {
        id: 'branch2',
        type: 'rectangle',
        position: { x: 600, y: 150 },
        data: {
          label: 'Branch 2',
          color: '#1F2937',
          backgroundColor: '#E5E7EB',
          borderColor: '#9CA3AF',
          fontSize: 14,
          fontWeight: 'normal',
          borderWidth: 1,
        },
      },
      {
        id: 'branch3',
        type: 'rectangle',
        position: { x: 200, y: 450 },
        data: {
          label: 'Branch 3',
          color: '#1F2937',
          backgroundColor: '#E5E7EB',
          borderColor: '#9CA3AF',
          fontSize: 14,
          fontWeight: 'normal',
          borderWidth: 1,
        },
      },
      {
        id: 'branch4',
        type: 'rectangle',
        position: { x: 600, y: 450 },
        data: {
          label: 'Branch 4',
          color: '#1F2937',
          backgroundColor: '#E5E7EB',
          borderColor: '#9CA3AF',
          fontSize: 14,
          fontWeight: 'normal',
          borderWidth: 1,
        },
      },
    ],
    edges: [
      {
        id: 'e1',
        source: 'central',
        target: 'branch1',
        type: 'curved',
        markerEnd: { type: 'arrowclosed', color: '#6B7280' },
      },
      {
        id: 'e2',
        source: 'central',
        target: 'branch2',
        type: 'curved',
        markerEnd: { type: 'arrowclosed', color: '#6B7280' },
      },
      {
        id: 'e3',
        source: 'central',
        target: 'branch3',
        type: 'curved',
        markerEnd: { type: 'arrowclosed', color: '#6B7280' },
      },
      {
        id: 'e4',
        source: 'central',
        target: 'branch4',
        type: 'curved',
        markerEnd: { type: 'arrowclosed', color: '#6B7280' },
      },
    ],
  },
  {
    id: 'project-roadmap',
    name: 'Project Roadmap',
    description: 'A timeline-based project roadmap template',
    preview: '🗺️',
    nodes: [
      {
        id: 'start',
        type: 'diamond',
        position: { x: 100, y: 300 },
        data: {
          label: 'Start',
          color: '#ffffff',
          backgroundColor: '#10B981',
          borderColor: '#047857',
          fontSize: 14,
          fontWeight: 'bold',
          borderWidth: 2,
        },
      },
      {
        id: 'phase1',
        type: 'rectangle',
        position: { x: 250, y: 300 },
        data: {
          label: 'Phase 1\nPlanning',
          color: '#1F2937',
          backgroundColor: '#FEF3C7',
          borderColor: '#F59E0B',
          fontSize: 14,
          fontWeight: 'normal',
          borderWidth: 1,
        },
      },
      {
        id: 'phase2',
        type: 'rectangle',
        position: { x: 400, y: 300 },
        data: {
          label: 'Phase 2\nDevelopment',
          color: '#1F2937',
          backgroundColor: '#DBEAFE',
          borderColor: '#3B82F6',
          fontSize: 14,
          fontWeight: 'normal',
          borderWidth: 1,
        },
      },
      {
        id: 'phase3',
        type: 'rectangle',
        position: { x: 550, y: 300 },
        data: {
          label: 'Phase 3\nTesting',
          color: '#1F2937',
          backgroundColor: '#FCE7F3',
          borderColor: '#EC4899',
          fontSize: 14,
          fontWeight: 'normal',
          borderWidth: 1,
        },
      },
      {
        id: 'end',
        type: 'diamond',
        position: { x: 700, y: 300 },
        data: {
          label: 'Launch',
          color: '#ffffff',
          backgroundColor: '#EF4444',
          borderColor: '#B91C1C',
          fontSize: 14,
          fontWeight: 'bold',
          borderWidth: 2,
        },
      },
    ],
    edges: [
      {
        id: 'r1',
        source: 'start',
        target: 'phase1',
        type: 'straight',
        markerEnd: { type: 'arrowclosed', color: '#6B7280' },
      },
      {
        id: 'r2',
        source: 'phase1',
        target: 'phase2',
        type: 'straight',
        markerEnd: { type: 'arrowclosed', color: '#6B7280' },
      },
      {
        id: 'r3',
        source: 'phase2',
        target: 'phase3',
        type: 'straight',
        markerEnd: { type: 'arrowclosed', color: '#6B7280' },
      },
      {
        id: 'r4',
        source: 'phase3',
        target: 'end',
        type: 'straight',
        markerEnd: { type: 'arrowclosed', color: '#6B7280' },
      },
    ],
  },
  {
    id: 'org-chart',
    name: 'Organization Chart',
    description: 'A hierarchical organization chart template',
    preview: '🏢',
    nodes: [
      {
        id: 'ceo',
        type: 'rectangle',
        position: { x: 350, y: 100 },
        data: {
          label: 'CEO',
          color: '#ffffff',
          backgroundColor: '#1F2937',
          borderColor: '#111827',
          fontSize: 16,
          fontWeight: 'bold',
          borderWidth: 2,
        },
      },
      {
        id: 'cto',
        type: 'rectangle',
        position: { x: 200, y: 250 },
        data: {
          label: 'CTO',
          color: '#1F2937',
          backgroundColor: '#DBEAFE',
          borderColor: '#3B82F6',
          fontSize: 14,
          fontWeight: 'normal',
          borderWidth: 1,
        },
      },
      {
        id: 'cmo',
        type: 'rectangle',
        position: { x: 500, y: 250 },
        data: {
          label: 'CMO',
          color: '#1F2937',
          backgroundColor: '#D1FAE5',
          borderColor: '#10B981',
          fontSize: 14,
          fontWeight: 'normal',
          borderWidth: 1,
        },
      },
      {
        id: 'dev1',
        type: 'circle',
        position: { x: 120, y: 400 },
        data: {
          label: 'Developer',
          color: '#1F2937',
          backgroundColor: '#F3F4F6',
          borderColor: '#9CA3AF',
          fontSize: 12,
          fontWeight: 'normal',
          borderWidth: 1,
        },
      },
      {
        id: 'dev2',
        type: 'circle',
        position: { x: 280, y: 400 },
        data: {
          label: 'Designer',
          color: '#1F2937',
          backgroundColor: '#F3F4F6',
          borderColor: '#9CA3AF',
          fontSize: 12,
          fontWeight: 'normal',
          borderWidth: 1,
        },
      },
      {
        id: 'mark1',
        type: 'circle',
        position: { x: 450, y: 400 },
        data: {
          label: 'Marketing\nSpecialist',
          color: '#1F2937',
          backgroundColor: '#F3F4F6',
          borderColor: '#9CA3AF',
          fontSize: 12,
          fontWeight: 'normal',
          borderWidth: 1,
        },
      },
      {
        id: 'mark2',
        type: 'circle',
        position: { x: 580, y: 400 },
        data: {
          label: 'Sales\nManager',
          color: '#1F2937',
          backgroundColor: '#F3F4F6',
          borderColor: '#9CA3AF',
          fontSize: 12,
          fontWeight: 'normal',
          borderWidth: 1,
        },
      },
    ],
    edges: [
      {
        id: 'o1',
        source: 'ceo',
        target: 'cto',
        type: 'straight',
        markerEnd: { type: 'arrowclosed', color: '#6B7280' },
      },
      {
        id: 'o2',
        source: 'ceo',
        target: 'cmo',
        type: 'straight',
        markerEnd: { type: 'arrowclosed', color: '#6B7280' },
      },
      {
        id: 'o3',
        source: 'cto',
        target: 'dev1',
        type: 'straight',
        markerEnd: { type: 'arrowclosed', color: '#6B7280' },
      },
      {
        id: 'o4',
        source: 'cto',
        target: 'dev2',
        type: 'straight',
        markerEnd: { type: 'arrowclosed', color: '#6B7280' },
      },
      {
        id: 'o5',
        source: 'cmo',
        target: 'mark1',
        type: 'straight',
        markerEnd: { type: 'arrowclosed', color: '#6B7280' },
      },
      {
        id: 'o6',
        source: 'cmo',
        target: 'mark2',
        type: 'straight',
        markerEnd: { type: 'arrowclosed', color: '#6B7280' },
      },
    ],
  },
];

export const createNodeFromTemplate = (template: Template, position: { x: number; y: number }) => {
  return template.nodes.map(node => ({
    ...node,
    id: uuidv4(),
    position: {
      x: node.position.x + position.x - 400,
      y: node.position.y + position.y - 300,
    },
  }));
};